### ISSUE TITLE
Binary polling broke profile moves

### ISSUE THREAD

**Issue by kmpeters** [epics-motor/motorAcsMotion#18]
It appears that binary polling broke profile moves.

Profile moves work using this commit:  8e9cd590e3ecb557b76fb228347e92fc8dc2412a

Profile moves hang using this commit:  e9615c7a59f0683761b57c112780f47c925e7229

**Comment by kmpeters** [comment]
Additional info about the problem:

Profile moves were hanging shortly after the execution of the profile move started.  Asyn traces showed a ``GSFREE`` query from the profile move thread in the middle of a ``writeReadBinary`` call from the poller thread just before the IOC hung:
```
2021/11/01 12:24:05.351 SPiiPlusController:getDoubleArray: start
2021/11/01 12:24:05.351 SPiiPlusController:getDoubleArray: var = XACC, ((0, 7), (0, 0))
2021/11/01 12:24:05.351 SPiiPlusController:writeReadBinary: start
2021/11/01 12:24:05.351 SPiiPlusController:writeReadBinary: output bytes = 23, output = ��
2021/11/01 12:24:05.351 164.54.104.47:701 write 23

d3 f0 12 00 25 3f 3f 08 58 41 43 43 28 30 2c 37 29 28 30 2c 
30 29 d6 
2021/11/01 12:24:05.351 SPiiPlusController:writeReadInt: output = ?GSFREE(0)
2021/11/01 12:24:05.351 164.54.104.47:701 read 69

e3 f0 40 00 00 00 00 00 d0 12 63 41 00 00 00 00 d0 12 63 41 
00 00 00 00 d0 12 63 41 00 00 00 00 d0 12 63 41 00 00 00 00 
d0 12 63 41 00 00 00 00 d0 12 63 41 00 00 00 00 d0 12 63 41 
00 00 00 00 d0 12 63 41 e6 
2021/11/01 12:24:05.352 SPiiPlusController:writeReadBinary:  input bytes = 69
2021/11/01 12:24:05.352 164.54.104.47:701 write 10

3f 47 53 46 52 45 45 28 30 29 
2021/11/01 12:24:05.352 SPiiPlusController:writeReadBinary: status = 0
```
The IOC was being run in gdb, so I could see what was going on.
```gdb
epics> ^C
Thread 1 "acsMotion" received signal SIGINT, Interrupt.
0x00007ffff5a5f884 in read () from /lib64/libc.so.6
Missing separate debuginfos, use: yum debuginfo-install krb5-libs-1.18.2-5.el8.x86_64 libcom_err-1.45.6-1.el8.x86_64 libgcc-8.3.1-5.1.el8.x86_64 libselinux-2.9-4.el8_3.x86_64 libstdc++-8.3.1-5.1.el8.x86_64 libtirpc-1.1.4-4.el8.x86_64 openssl-libs-1.1.1g-15.el8_3.x86_64 pcre2-10.32-2.el8.x86_64 zlib-1.2.11-16.2.el8_3.x86_64
(gdb) bt
#0  0x00007ffff5a5f884 in read () from /lib64/libc.so.6
#1  0x00007ffff59efc08 in __GI__IO_file_underflow () from /lib64/libc.so.6
#2  0x00007ffff59f0d66 in _IO_default_uflow () from /lib64/libc.so.6
#3  0x00007ffff59eb2f0 in getc () from /lib64/libc.so.6
#4  0x00007ffff66b179c in epicsReadline (prompt=0x7ffff66cb8a0 "epics> ", context=0x7f9250) at ../osi/epicsReadline.c:108
#5  0x00007ffff66a04b8 in iocshBody (pathname=0x0, commandLine=0x0, macros=0x0) at ../iocsh/iocsh.cpp:709
#6  0x00007ffff66a1112 in iocshLoad (pathname=0x0, macros=0x0) at ../iocsh/iocsh.cpp:1033
#7  0x00007ffff66a10b2 in iocsh (pathname=0x0) at ../iocsh/iocsh.cpp:1019
#8  0x0000000000406f7c in main (argc=2, argv=0x7fffffffcf88) at ../acsMotionMain.cpp:20
(gdb) info thread
  Id   Target Id                                             Frame 
* 1    Thread 0x7ffff7fb9d40 (LWP 2793248) "acsMotion"       0x00007ffff5a5f884 in read () from /lib64/libc.so.6
  3    Thread 0x7ffff7fb6700 (LWP 2793256) "errlog"          0x00007ffff576030c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  4    Thread 0x7ffff7f35700 (LWP 2793257) "timerQueue"      0x00007ffff576065a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  5    Thread 0x7ffff2de1700 (LWP 2793258) "timerQueue"      0x00007ffff576065a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  6    Thread 0x7ffff2ce0700 (LWP 2793259) "ACS1_ETH"        0x00007ffff575c45f in __pthread_mutex_lock_full () from /lib64/libpthread.so.0
  7    Thread 0x7ffff2bdf700 (LWP 2793260) "taskwd"          0x00007ffff576065a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  8    Thread 0x7ffff2b5e700 (LWP 2793261) "ACS1"            0x00007ffff575c45f in __pthread_mutex_lock_full () from /lib64/libpthread.so.0
  10   Thread 0x7ffff295c700 (LWP 2793263) "motorPoller"     0x00007ffff575c45f in __pthread_mutex_lock_full () from /lib64/libpthread.so.0
  11   Thread 0x7ffff285b700 (LWP 2793264) "SPiiPlusProfile" 0x00007ffff5a63cf1 in poll () from /lib64/libc.so.6
  12   Thread 0x7ffff275a700 (LWP 2793265) "timerQueue"      0x00007ffff576065a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  13   Thread 0x7ffff35e2700 (LWP 2793266) "cbLow"           0x00007ffff576030c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  14   Thread 0x7ffff2659700 (LWP 2793267) "cbMedium"        0x00007ffff576030c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  15   Thread 0x7ffff2458700 (LWP 2793268) "cbHigh"          0x00007ffff576030c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  16   Thread 0x7ffff2257700 (LWP 2793269) "dbCaLink"        0x00007ffff576030c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  17   Thread 0x7ffff2056700 (LWP 2793270) "scanOnce"        0x00007ffff576030c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  18   Thread 0x7ffff1e55700 (LWP 2793271) "scan-10"         0x00007ffff576065a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  19   Thread 0x7ffff1c54700 (LWP 2793272) "scan-5"          0x00007ffff576065a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  20   Thread 0x7ffff1a53700 (LWP 2793273) "scan-2"          0x00007ffff576065a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  21   Thread 0x7ffff1852700 (LWP 2793274) "scan-1"          0x00007ffff576065a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  22   Thread 0x7ffff1651700 (LWP 2793275) "scan-0.5"        0x00007ffff576065a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  23   Thread 0x7ffff1450700 (LWP 2793276) "scan-0.2"        0x00007ffff576065a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  24   Thread 0x7ffff124f700 (LWP 2793277) "scan-0.1"        0x00007ffff576065a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  25   Thread 0x7ffff104e700 (LWP 2793278) "CAS-TCP"         0x00007ffff5a70917 in accept4 () from /lib64/libc.so.6
  26   Thread 0x7ffff0f4d700 (LWP 2793279) "CAS-UDP"         0x00007ffff5a7023a in recvfrom () from /lib64/libc.so.6
  27   Thread 0x7ffff0e4c700 (LWP 2793280) "CAS-beacon"      0x00007ffff5a3b018 in nanosleep () from /lib64/libc.so.6
  28   Thread 0x7ffff0dcb700 (LWP 2793281) "motorUtil"       0x00007ffff576030c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  29   Thread 0x7ffff0bc9700 (LWP 2793283) "CAC-event"       0x00007ffff576030c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  30   Thread 0x7ffff0cca700 (LWP 2793282) "CAC-event"       0x00007ffff576030c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  31   Thread 0x7ffff2a5d700 (LWP 2793293) "CAS-event"       0x00007ffff576030c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  32   Thread 0x7ffff0a4e700 (LWP 2793294) "CAS-client"      0x00007ffff5a70176 in recv () from /lib64/libc.so.6
(gdb) thread 10
[Switching to thread 10 (Thread 0x7ffff295c700 (LWP 2793263))]
#0  0x00007ffff575c45f in __pthread_mutex_lock_full () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007ffff575c45f in __pthread_mutex_lock_full () from /lib64/libpthread.so.0
#1  0x00007ffff66b4cc3 in mutexLock (id=0x6f59a0) at ../osi/os/posix/osdMutex.c:116
#2  0x00007ffff66b4de3 in epicsMutexOsdLock (pmutex=0x6f59a0) at ../osi/os/posix/osdMutex.c:163
#3  0x00007ffff66ad889 in epicsMutexLock (pmutexNode=0x6f59d0) at ../osi/epicsMutex.cpp:150
#4  0x00007ffff74e97c3 in lockPort (pasynUser=0x6faed8) at ../../asyn/asynDriver/asynManager.c:1752
#5  0x00007ffff750259a in setInputEos (pasynUser=0x6faed8, eos=0x7ffff7bcf1f8 "\r", eoslen=1) at ../../asyn/interfaces/asynOctetSyncIO.c:306
#6  0x00007ffff7bc5774 in SPiiPlusController::writeReadBinary (this=0x6f8aa0, output=0x7ffff295bb50 "\323\360\022", outBytes=23, input=0x6f9ee0 "", inBytes=69, dataBytes=0x7ffff295bb38, sliceAvailable=0x7ffff295bb37)
    at ../SPiiPlusDriver.cpp:550
#7  0x00007ffff7bc5bce in SPiiPlusController::getDoubleArray (this=0x6f8aa0, output=0x6f9ee0 "", var=0x7ffff7bcf373 "XACC", idx1start=0, idx1end=7, idx2start=0, idx2end=0) at ../SPiiPlusDriver.cpp:614
#8  0x00007ffff7bc6916 in SPiiPlusController::poll (this=0x6f8aa0) at ../SPiiPlusDriver.cpp:733
#9  0x00007ffff79ade8a in asynMotorController::asynMotorPoller (this=0x6f8aa0) at ../asynMotorController.cpp:649
#10 0x00007ffff79add77 in asynMotorPollerC (drvPvt=0x6f8aa0) at ../asynMotorController.cpp:604
#11 0x00007ffff66b2dd8 in start_routine (arg=0x71b720) at ../osi/os/posix/osdThread.c:418
#12 0x00007ffff575a15a in start_thread () from /lib64/libpthread.so.0
#13 0x00007ffff5a6ef73 in clone () from /lib64/libc.so.6
(gdb) frame 6
#6  0x00007ffff7bc5774 in SPiiPlusController::writeReadBinary (this=0x6f8aa0, output=0x7ffff295bb50 "\323\360\022", outBytes=23, input=0x6f9ee0 "", inBytes=69, dataBytes=0x7ffff295bb38, sliceAvailable=0x7ffff295bb37)
    at ../SPiiPlusDriver.cpp:550
550[5C[8CpasynOctetSyncIO->setInputEos(pasynUserController_, "\r", 1);
(gdb) list
545[5C[8C[8C*sliceAvailable = false;
546[5C[8C[8CasynPrint(this->pasynUserSelf, ASYN_TRACE_ERROR, "%s:%s: Binary read failed (asyn): status=%i, nread=%li\n", driverName, functionName, status, nread);
547[5C[8C}
548[5C[8C
549[5C[8C// Restore the EOS characters
550[5C[8CpasynOctetSyncIO->setInputEos(pasynUserController_, "\r", 1);
551[5C[8CpasynOctetSyncIO->setOutputEos(pasynUserController_, "\r", 1);
552[5C[8C
553[5C[8Cunlock();
554[5C[8C
(gdb) 
thread 11
[Switching to thread 11 (Thread 0x7ffff285b700 (LWP 2793264))]
#0  0x00007ffff5a63cf1 in poll () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff5a63cf1 in poll () from /lib64/libc.so.6
#1  0x00007ffff74f4a34 in readIt (drvPvt=0x6f1670, pasynUser=0x6faed8, data=0x6f7a50 "\343\360@", maxchars=2048, nbytesTransfered=0x7ffff2859da8, gotEom=0x7ffff2859da4) at ../../asyn/drvAsynSerial/drvAsynIPPort.c:764
#2  0x00007ffff750143a in readIt (drvPvt=0x6f7870, pasynUser=0x6faed8, data=0x6f7a50 "\343\360@", maxchars=2048, nbytesTransfered=0x7ffff2859da8, eomReason=0x7ffff2859da4) at ../../asyn/interfaces/asynOctetBase.c:231
#3  0x00007ffff750c3a1 in readIt (ppvt=0x6f7970, pasynUser=0x6faed8, data=0x7ffff285a090 "", maxchars=256, nbytesTransfered=0x7ffff2859ef0, eomReason=0x7ffff2859e9c) at ../../asyn/miscellaneous/asynInterposeEos.c:231
#4  0x00007ffff75023ba in writeRead (pasynUser=0x6faed8, write_buffer=0x7ffff285a1d0 "?GSFREE(0)", write_buffer_len=10, read_buffer=0x7ffff285a090 "", read_buffer_len=256, timeout=-1, nbytesOut=0x7ffff2859ea0, 
    nbytesIn=0x7ffff2859ef0, eomReason=0x7ffff2859e9c) at ../../asyn/interfaces/asynOctetSyncIO.c:262
#5  0x00007ffff79ae45e in asynMotorController::writeReadController (this=0x6f8aa0, output=0x7ffff285a1d0 "?GSFREE(0)", input=0x7ffff285a090 "", maxChars=256, nread=0x7ffff2859ef0, timeout=-1) at ../asynMotorController.cpp:790
#6  0x00007ffff7bc41a9 in SPiiPlusController::writeReadInt (this=0x6f8aa0, cmd=..., val=0x7ffff285a2ec) at ../SPiiPlusDriver.cpp:357
#7  0x00007ffff7bcba8a in SPiiPlusController::runProfile (this=0x6f8aa0) at ../SPiiPlusDriver.cpp:1936
#8  0x00007ffff7bca90b in SPiiPlusController::profileThread (this=0x6f8aa0) at ../SPiiPlusDriver.cpp:1721
#9  0x00007ffff7bca8dc in SPiiPlusProfileThreadC (pPvt=0x6f8aa0) at ../SPiiPlusDriver.cpp:1713
#10 0x00007ffff66b2dd8 in start_routine (arg=0x71ba10) at ../osi/os/posix/osdThread.c:418
#11 0x00007ffff575a15a in start_thread () from /lib64/libpthread.so.0
#12 0x00007ffff5a6ef73 in clone () from /lib64/libc.so.6
(gdb) frame 6
#6  0x00007ffff7bc41a9 in SPiiPlusController::writeReadInt (this=0x6f8aa0, cmd=..., val=0x7ffff285a2ec) at ../SPiiPlusDriver.cpp:357
357[5C[8CasynStatus status = this->writeReadController(cmd.str().c_str(), inString, 256, &response, -1);
(gdb) list
352[5C[8Cstd::fill(inString, inString + 256, '\0');
353[5C[8C
354[5C[8CasynPrint(this->pasynUserSelf, ASYN_TRACEIO_DRIVER, "%s:%s: output = %s\n", driverName, functionName, cmd.str().c_str());
355[5C[8C
356[5C[8Csize_t response;
357[5C[8CasynStatus status = this->writeReadController(cmd.str().c_str(), inString, 256, &response, -1);
358[5C[8C
359[5C[8CasynPrint(this->pasynUserSelf, ASYN_TRACEIO_DRIVER, "%s:%s:  input = %s\n", driverName, functionName, inString);
360[5C[8CasynPrint(this->pasynUserSelf, ASYN_TRACEIO_DRIVER, "%s:%s: status = %i\n", driverName, functionName, status);
361[5C[8C
```
